---
# handlers file for grafanaserv
- name: "Reinicia el servicio de grafana."
  service:
    name: grafana-server
    state: restarted
  listen: restart_grafana

- name: "Reinicia el servicio de Prometheus"
  service:
    name: prometheus
    state: restarted
  listen: restart_prometheus

- name: "Reload systemd"
  command: systemctl daemon-reload
  listen: systemd_reload
